### PR TITLE
Chronus

### PR DESCRIPTION
**Pull request by charliemirabile**
This is an initial version of a new 'chronus' container that manages the list of assignments and their due dates and generates peer review assignments.

Currently email is still not added to the journal automatically. The expectation for making this work in production is that a cronjob should be setup that releases all email every 5m (or something like that) by executing `podman-compose exec pop /usr/local/bin/init_journal /var/lib/email/journal/journal /var/lib/email/journal/temp /var/lib/email/mail`.

This system merely regulates restricting access to the latest emails for specific students based on whether or not they submitted.

### CODE REVIEW

**Comment by charliemirabile** [comment]
The expectation for using this system, is that a cronjob should be setup that releases all email every 5m (or something like that) by executing `podman exec singularity_pop_1 /usr/local/bin/init_journal /var/lib/email/journal/journal /var/lib/email/journal/temp /var/lib/email/mail`. This script will take care of allowing and restricting access to email based on who has submitted.

**Comment by theyoyojo** [comment]
looks good except my test user can't see the peer review when triggering intitial.py after running email-test.sh on email-test-4

**Comment by theyoyojo** [comment]
the peer review email is present in the volumes though

**Review by theyoyojo — APPROVED** [review]
lgtm

**Pull request merged**
