### PR TITLE
Web cleanup

### PR DESCRIPTION
**Pull request by charliemirabile**
spring cleaning on all the random files living in the root of the kdlp.underground.software folder
BEFORE:
```
$ git show master:kdlp.underground.software/
tree master:kdlp.underground.software/

400.md
401.md
403.md
404.md
405.md
500.md
502.md
CNAME
README.md
android-chrome-192x192.png
android-chrome-512x512.png
apple-touch-icon.png
course/
faq.md
favicon-16x16.png
favicon-32x32.png
favicon.ico
images/
index.md
lpc2023.html
site.webmanifest
slides_src/
style.css
```
AFTER:
```
$ git show web_cleanup:kdlp.underground.software/
tree web_cleanup:kdlp.underground.software/

400.md
401.md
403.md
404.md
405.md
500.md
502.md
README.md
assets/
course/
faq.md
images/
index.md
lpc2023.html
slides_src/
```

### CODE REVIEW

**Comment by theyoyojo** [comment]
Seems like some of the icons are going missing?

**Comment by charliemirabile** [comment]
can you be more specific? I don't see any missing icons

**Comment by theyoyojo** [comment]
looks like the two favicon*.png files are deleted

**Comment by charliemirabile** [comment]
> looks like the two favicon*.png files are deleted

yes, that is correct. Those two files are not something that clients request. They get favicon.ico which is a combination file that includes both sizes. The two .png files were just the source for creating that .ico file as I explained in the commit that removed them. The favicon still shows up as expected because they are not used.

**Review by theyoyojo — APPROVED** [review]
lgtm

**Pull request merged**
