### PR TITLE
Dashboard overhaul

### PR DESCRIPTION
**Pull request by charliemirabile**
After one year, we have finally surpassed what we had for a dashboard

### CODE REVIEW

**Comment by theyoyojo** [comment]
fails style checks

**Comment by theyoyojo** [comment]
> fails style checks

actually this may be a fedora 37 issue so perhaps disregard

**Comment by theyoyojo** [comment]
Fixes: #147 
Fixes: #137 
Fixes: #125 
Fixes: #124 
Fixes: #66

**Comment by charliemirabile** [comment]
superseded by #186

**Pull request closed without merging**
